# Site settings
title: "Vince Tse"
description: "Software Enginerd. Learn & Teach. #WhatProblemAreYouTryingToSolve"
url: 'https://www.vincetse.com'
baseurl: '/'
google_analytics: 'UA-75285770-1'
# disqus_shortname: 'your-disqus-name'
profile_image: 'images/vincetse-2016-05-29.jpg'
cover_image: 'images/highways-interchange-2048x1365.jpg'
social_media:
  title: "Software Enginerd. Learn & Teach. #WhatProblemAreYouTryingToSolve"
  description: "Software Enginerd. Learn & Teach. #WhatProblemAreYouTryingToSolve"
  profile_image: 'images/vincetse-2016-05-29.jpg'
  type: 'website'

author:
  name: 'Vince Tse'
  show_blog: false
  gplus_profile_url: "https://plus.google.com/u/0/116496789423041407327"
  twitter_username: vincetse
  github_username:  vincetse
  linkedin_username:  vincetse
  medium_username: vincetse
  instagram_username: v1ncetse
  show_rss: false

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
